version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - apt-get update -y
#      - apt-get install -y maven
      - apt-get install -y awscli
  build:
    commands:
#      - mvn install | tee mvn-output.txt
#      - version=$(awk '{ if ($2 == "Building") print $4 }' mvn-output.txt | grep -v jar)
#      - app_name=$(awk '{ if ($2 == "Building") print $3 }' mvn-output.txt | grep -v jar)
#      - echo preparing to copy ${app_name}-${version}.jar to ${ARTIFACT_BUCKET_STORE}
      - aws sts get-caller-identity
#      - aws s3api list-buckets --query Owner.ID
      - aws s3api list-objects --bucket talytica --prefix artifacts
#      - aws s3 cp target/${app_name}-${version}.jar s3://${ARTIFACT_BUCKET_STORE}
      - aws s3 cp pom.xml s3://${ARTIFACT_BUCKET_STORE}/${app_name}-${version}.pom